# Generated by Django 4.1.7 on 2023-04-17 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawyerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Lawywer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification", models.FileField(upload_to="lawyers/certificates/")),
                (
                    "experience",
                    models.IntegerField(default=0, verbose_name="years of experience"),
                ),
                ("organisation", models.CharField(max_length=50)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("slug", models.SlugField(default=None)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.IntegerField(default=0)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "lwyr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lwyr",
                        to="account.lawywer",
                        verbose_name="lawyer",
                    ),
                ),
                (
                    "usr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usr",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("startTime", models.DateTimeField()),
                ("endtTime", models.DateTimeField()),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lawyer",
                        to="account.lawywer",
                    ),
                ),
            ],
        ),
    ]
