# Generated by Django 4.1.7 on 2024-05-17 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='thumb.jpg', upload_to='post/thumb/')),
                ('title', models.CharField(default=None, max_length=9000)),
                ('intro', models.TextField(blank=True, default=None, verbose_name='introduction')),
                ('body', models.TextField(blank=True, default=None, verbose_name='content')),
                ('v_link', models.TextField(blank=True, default=None, verbose_name='video link')),
                ('m_link', models.TextField(blank=True, default=None, verbose_name='music link')),
                ('s_link', models.TextField(blank=True, default=None, verbose_name='social link')),
                ('upload', models.FileField(blank=True, upload_to='post/upload/')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=None)),
                ('stamp', models.DateField(auto_now_add=True)),
                ('l_updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-stamp',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9000)),
                ('slug', models.SlugField(default=None)),
                ('l_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category', verbose_name='category'),
        ),
    ]
